/** Files generated by `agent create <name>`. */
export function scaffold(name: string): Record<string, string> {
  const camel = name.replace(/-([a-z0-9])/g, (_m, c: string) => c.toUpperCase());
  return {
    "agent.ts": `import { createRuntime, defineAgent } from "@agent-farmework/core";
import { createScriptedProvider } from "@agent-farmework/core/testing";
import { ToolRuntime, defineTool } from "@agent-farmework/tools";
import { z } from "zod";

// Replace with a real provider, e.g. anthropicProvider() from @agent-farmework/provider-anthropic.
const provider = createScriptedProvider([{ text: "Hello from ${name}!" }], { id: "anthropic" });

export const lookupTool = defineTool({
  name: "lookup",
  description: "Look up a fact by key",
  input: z.object({ key: z.string() }),
  permissions: ["facts.read"],
  execute: async ({ key }) => ({ key, value: "42" }),
});

export const runtime = createRuntime({ providers: [provider], tools: new ToolRuntime() });

export const agent = defineAgent({
  name: "${name}",
  version: "0.1.0",
  model: { providerId: "anthropic", modelId: "claude-opus-5" },
  instructions: "You are ${name}. Use tools for facts. Be concise.",
  tools: [lookupTool],
  permissions: ["facts.read"],
  limits: { maxSteps: 6, maxToolCalls: 5, maxCost: 0.1, timeoutMs: 60_000 },
  runtime,
});
`,
    "agent.test.ts": `import { createRuntime, defineAgent } from "@agent-farmework/core";
import { createScriptedProvider } from "@agent-farmework/core/testing";
import { ToolRuntime } from "@agent-farmework/tools";
import { expect, test } from "vitest";
import { agent, lookupTool } from "./agent.js";

test("${name} answers using the lookup tool", async () => {
  const provider = createScriptedProvider(
    [{ toolCalls: [{ id: "c1", name: "lookup", arguments: { key: "answer" } }] }, { text: "The answer is 42." }],
    { id: "anthropic" },
  );
  const runtime = createRuntime({ providers: [provider], tools: new ToolRuntime() });
  const ${camel} = defineAgent({ ...agent.config, tools: [lookupTool], runtime });
  const result = await ${camel}.run({ input: "What is the answer?", user: { userId: "u", permissions: ["facts.read"] } });
  expect(result.status).toBe("COMPLETED");
  expect(result.output).toContain("42");
});
`,
    "eval.ts": `import { defineDataset, defineEvaluation, evaluators } from "@agent-farmework/evaluation";
import { agent } from "./agent.js";

export const evaluation = defineEvaluation({
  name: "${name}-regression",
  dataset: defineDataset("${name}-golden", [{ id: "greeting", input: "Say hello", expected: "hello" }]),
  target: agent,
  evaluators: [evaluators.status(), evaluators.contains(), evaluators.cost(0.05)],
  thresholds: { minPassRate: 1 },
});
`,
    "agent.manifest.json": `${JSON.stringify(
      {
        name,
        version: "0.1.0",
        description: `${name} agent`,
        model: { provider: "anthropic", model: "claude-opus-5" },
        instructions: `You are ${name}. Use tools for facts. Be concise.`,
        tools: ["lookup"],
        security: { permissions: ["facts.read"] },
        limits: { maxSteps: 6, maxToolCalls: 5, maxCost: 0.1, timeoutMs: 60000 },
      },
      null,
      2,
    )}\n`,
  };
}
